### ISSUE TITLE
PersistenceProvider.GetProcessInstancesAsync SQL Error

### ISSUE THREAD

**Issue by LiubomyrSkalskyi** [optimajet/WorkflowEngine.NET#128]
System.AggregateException: 'One or more errors occurred. (An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.)'

**Comment by betine** [comment]
Can you send us a full stack trace of this exception?

**Comment by LiubomyrSkalskyi** [comment]
at OptimaJet.Workflow.DbPersistence.DbObject`1.<SelectAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at OptimaJet.Workflow.DbPersistence.DbObject`1.<SelectAllWithPagingAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at OptimaJet.Workflow.DbPersistence.MSSQLProvider.<GetProcessInstancesAsync>d__22.MoveNext()

**Comment by LiubomyrSkalskyi** [comment]
Here is Inner Exception stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OptimaJet.Workflow.DbPersistence.DbObject`1.<SelectInternalAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at OptimaJet.Workflow.DbPersistence.DbObject`1.<SelectAsync>d__19.MoveNext()

**Comment by betine** [comment]
Can you please describe the case when this exception occurs? It is not obvious from this stack trace.

**Comment by LiubomyrSkalskyi** [comment]
I'm just testing the package functionality to be sure it fits with my current project.
I'm calling **WorkflowInit.Runtime.PersistenceProvider.GetProcessInstancesAsync()** to load the processes
It is the Console app like in the **How to Integrate** article, running .Net Core 3.1 connected with MSSQL Server

**Comment by LiubomyrSkalskyi** [comment]
![image](https://user-images.githubusercontent.com/80105283/166257705-31516bba-d58f-46d4-af8e-b0d467715bd5.png)

**Comment by LiubomyrSkalskyi** [comment]
Does it make sense? Because I didn't find any documentation on that method

**Comment by betine** [comment]
Now it is clear, this bug will be fixed soon. Thank you for the report.

**Comment by Andrew-Solo** [comment]
Hello, I took this bug to work.

Please, send:
1. Full code that causes this exception.
2. Version of dotnet, Workflow Engine and SqlServer used.
