### ISSUE TITLE
workflow database

### ISSUE THREAD

**Issue by jerrylisuzhou** [optimajet/WorkflowEngine.NET#76]
Does workflow engine will do a database index rebuild work?   When my database was full and I shrink the database , I find one command maybe from  workflow to rebuild index  , but I am not confirmed .

**Comment by optimajet** [comment]
Hi, the workflow engine does not rebuild indexes in the database as it is an embeddable component.

**Comment by sandeepModapathi** [comment]
faced issue in _layout.cshtml, 
ViewBag.Title is null 

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: args
  Source=mscorlib
  StackTrace:
   at System.String.Format(String format, Object[] args)
   at ASP._Page_Views_Shared__Layout_cshtml.Execute() in d:\DotNetMVC\workflow\WorkflowEngine.NET-master\Samples\ASP.NET MVC\MSSQL\WF.Sample\Views\Shared\_Layout.cshtml:line 3
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer)
   at System.Web.WebPages.HelperResult.WriteTo(TextWriter writer)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

  This exception was originally thrown at this call stack:
    [External Code]
    ASP._Page_Views_Shared__Layout_cshtml.Execute() in _Layout.cshtml
    [External Code]

**Comment by optimajet** [comment]
It doesn't look like WorkflowEngine exception.
